BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "TReportChat" (
	"pReport"	INTEGER NOT NULL,
	"sBody"	TEXT NOT NULL,
	"bCity"	INTEGER NOT NULL,
	"dtCreated"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "TReport" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"sContent"	TEXT NOT NULL,
	"sPhoto"	TEXT,
	"dtCreated"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "TMessage" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"sBody"	TEXT NOT NULL,
	"sUrl"	TEXT,
	"dtCreated"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
